### ISSUE TITLE
How do you determine which packages need the "-ffat-lto-objects" flag?

### ISSUE THREAD

**Issue by onodera-punpun** [Admicos/kiss-repo#2]
I'm not seeing many of the packages you give this flag in Gentoo-LTO, nor can I find much info online.

**Comment by Admicos** [comment]
> How do you determine which packages need the  "-ffat-lto-objects"
> flag? 

I just tried re-compiling my system, and changed flags until the
compilation worked, so my solution might not be the best one.

Also, I *currently* do not use KISS, so these flags might be outdated.

**Comment by onodera-punpun** [comment]
Thanks!
